# Generated by Django 2.1.5 on 2019-02-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40, verbose_name='姓名')),
                ('telephone', models.CharField(default='', max_length=11, verbose_name='手机号')),
                ('key', models.CharField(default='', max_length=20, verbose_name='授权码')),
                ('idcard', models.CharField(default='', max_length=40, verbose_name='身份证号')),
                ('wecaht', models.CharField(default='', max_length=20, verbose_name='微信号')),
                ('email', models.EmailField(default='', max_length=20, verbose_name='邮箱')),
                ('address', models.CharField(default='', max_length=100, verbose_name='代理地址')),
                ('profession', models.CharField(default='', max_length=20, verbose_name='代理职业')),
                ('work_place', models.CharField(default='', max_length=40, verbose_name='工作单位')),
                ('message', models.CharField(default='', max_length=500, verbose_name='用户留言信息')),
            ],
            options={
                'verbose_name': '代理钥匙',
                'verbose_name_plural': '代理钥匙',
            },
        ),
    ]
