# Generated by Django 2.1.5 on 2019-02-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentkeys', '0002_auto_20190211_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='certificate',
            field=models.CharField(default='', max_length=30, verbose_name='授权书'),
        ),
    ]
